import SwiftUI

// MARK: - Card Detail View

/// Full detail editor for a Kanban card shown in a sheet/popover
struct CardDetailView: View {
    @Environment(\.dismiss) private var dismiss

    let card: KanbanCard
    let columnId: UUID
    let onUpdate: (KanbanCard) -> Void
    let onDelete: () -> Void
    let onClaim: (() -> Void)?

    @State private var editedCard: KanbanCard
    @State private var isEditingTitle = false
    @State private var isEditingDescription = false
    @State private var showingDeleteConfirmation = false
    @State private var showingLabelPicker = false
    @State private var hasUnsavedChanges = false

    // Auto-save debounce
    @State private var autoSaveTask: Task<Void, Never>?

    init(
        card: KanbanCard,
        columnId: UUID,
        onUpdate: @escaping (KanbanCard) -> Void,
        onDelete: @escaping () -> Void,
        onClaim: (() -> Void)? = nil
    ) {
        self.card = card
        self.columnId = columnId
        self.onUpdate = onUpdate
        self.onDelete = onDelete
        self.onClaim = onClaim
        _editedCard = State(initialValue: card)
    }

    var body: some View {
        VStack(spacing: 0) {
            // Header with close and action buttons
            headerView
                .padding()
                .background(Color.rtBackgroundDark)
                .overlay(
                    Rectangle()
                        .frame(height: 1)
                        .foregroundColor(.rtBorderSubtle),
                    alignment: .bottom
                )

            // Main content
            ScrollView {
                VStack(alignment: .leading, spacing: 20) {
                    // Title editor
                    titleSection

                    // Description editor
                    descriptionSection

                    // Labels
                    labelsSection

                    // Metadata
                    metadataSection

                    // Card history/info
                    infoSection
                }
                .padding()
            }

            // Footer with delete button
            footerView
                .padding()
                .background(Color.rtBackgroundDark)
                .overlay(
                    Rectangle()
                        .frame(height: 1)
                        .foregroundColor(.rtBorderSubtle),
                    alignment: .top
                )
        }
        .frame(minWidth: 500, minHeight: 600)
        .background(Color.rtBackgroundLight)
        .onAppear {
            // Focus on title if it's a new card
            if card.title.isEmpty {
                isEditingTitle = true
            }
        }
        .sheet(isPresented: $showingLabelPicker) {
            LabelPickerView(
                selectedLabels: $editedCard.labels,
                onDismiss: {
                    showingLabelPicker = false
                    saveChanges()
                }
            )
        }
        .alert("Delete Card?", isPresented: $showingDeleteConfirmation) {
            Button("Cancel", role: .cancel) {}
            Button("Delete", role: .destructive) {
                onDelete()
                dismiss()
            }
        } message: {
            Text("This card will be permanently deleted. This action cannot be undone.")
        }
        .onKeyboardShortcut(.escape) {
            dismiss()
        }
    }

    // MARK: - Header View

    private var headerView: some View {
        HStack {
            // Source badge
            HStack(spacing: 6) {
                Image(systemName: editedCard.source.iconName)
                    .font(.system(size: 12))
                Text(editedCard.source.displayName)
                    .font(.system(size: 11, weight: .medium, design: .monospaced))

                if editedCard.isAutoGenerated, let onClaim = onClaim {
                    Button(action: {
                        onClaim()
                        dismiss()
                    }) {
                        Text("Claim Card")
                            .font(.system(size: 10, weight: .medium, design: .monospaced))
                            .foregroundColor(.rtAccentGreen)
                            .padding(.horizontal, 8)
                            .padding(.vertical, 4)
                            .background(Color.rtAccentGreen.opacity(0.15))
                            .cornerRadius(4)
                    }
                    .buttonStyle(.plain)
                }
            }
            .foregroundColor(.rtTextSecondary)

            Spacer()

            // Close button
            Button(action: {
                dismiss()
            }) {
                Image(systemName: "xmark.circle.fill")
                    .font(.system(size: 18))
                    .foregroundColor(.rtMuted)
            }
            .buttonStyle(.plain)
            .help("Close (Esc)")
        }
    }

    // MARK: - Title Section

    private var titleSection: some View {
        VStack(alignment: .leading, spacing: 8) {
            Text("Title")
                .font(.system(size: 10, weight: .semibold, design: .monospaced))
                .foregroundColor(.rtTextSecondary)
                .textCase(.uppercase)

            TextField("Card title...", text: $editedCard.title, axis: .vertical)
                .textFieldStyle(.plain)
                .font(.system(size: 16, weight: .semibold, design: .monospaced))
                .foregroundColor(.rtTextPrimary)
                .padding(10)
                .background(Color.rtBackgroundDark.opacity(0.5))
                .cornerRadius(6)
                .overlay(
                    RoundedRectangle(cornerRadius: 6)
                        .stroke(isEditingTitle ? Color.rtAccentGreen : Color.rtBorderSubtle, lineWidth: 1)
                )
                .onChange(of: editedCard.title) { _ in
                    hasUnsavedChanges = true
                }
                .onSubmit {
                    saveChanges()
                }
                .onFocus { focused in
                    isEditingTitle = focused
                }
        }
    }

    // MARK: - Description Section

    private var descriptionSection: some View {
        VStack(alignment: .leading, spacing: 8) {
            Text("Description")
                .font(.system(size: 10, weight: .semibold, design: .monospaced))
                .foregroundColor(.rtTextSecondary)
                .textCase(.uppercase)

            TextEditor(text: $editedCard.description)
                .font(.system(size: 12, design: .monospaced))
                .foregroundColor(.rtTextPrimary)
                .frame(minHeight: 120)
                .padding(10)
                .background(Color.rtBackgroundDark.opacity(0.5))
                .cornerRadius(6)
                .overlay(
                    RoundedRectangle(cornerRadius: 6)
                        .stroke(isEditingDescription ? Color.rtAccentGreen : Color.rtBorderSubtle, lineWidth: 1)
                )
                .onChange(of: editedCard.description) { _ in
                    hasUnsavedChanges = true
                }
                .onFocus { focused in
                    isEditingDescription = focused
                }
        }
    }

    // MARK: - Labels Section

    private var labelsSection: some View {
        VStack(alignment: .leading, spacing: 8) {
            HStack {
                Text("Labels")
                    .font(.system(size: 10, weight: .semibold, design: .monospaced))
                    .foregroundColor(.rtTextSecondary)
                    .textCase(.uppercase)

                Spacer()

                Button(action: {
                    showingLabelPicker = true
                }) {
                    HStack(spacing: 4) {
                        Image(systemName: "plus.circle.fill")
                            .font(.system(size: 12))
                        Text("Add Label")
                            .font(.system(size: 10, weight: .medium, design: .monospaced))
                    }
                    .foregroundColor(.rtAccentGreen)
                }
                .buttonStyle(.plain)
            }

            if editedCard.labels.isEmpty {
                Text("No labels yet")
                    .font(.system(size: 11, design: .monospaced))
                    .foregroundColor(.rtMuted)
                    .padding(.vertical, 8)
            } else {
                FlowLayout(spacing: 8) {
                    ForEach(editedCard.labels) { label in
                        LabelChip(
                            label: label,
                            onRemove: {
                                removeLabel(label)
                            }
                        )
                    }
                }
            }
        }
    }

    // MARK: - Metadata Section

    private var metadataSection: some View {
        VStack(alignment: .leading, spacing: 12) {
            Text("Details")
                .font(.system(size: 10, weight: .semibold, design: .monospaced))
                .foregroundColor(.rtTextSecondary)
                .textCase(.uppercase)

            VStack(spacing: 10) {
                // Status
                MetadataRow(
                    icon: editedCard.status.iconName,
                    label: "Status",
                    value: editedCard.status.displayName
                )

                // Priority
                MetadataRow(
                    icon: editedCard.priority.iconName,
                    label: "Priority",
                    value: editedCard.priority.displayName,
                    valueColor: priorityColor
                )

                // Assignee
                if let assignee = editedCard.assignee, !assignee.isEmpty {
                    MetadataRow(
                        icon: "person.circle",
                        label: "Assignee",
                        value: formatAssignee(assignee)
                    )
                }

                // Ticket reference
                if let ticketRef = editedCard.ticketRef {
                    MetadataRow(
                        icon: "ticket",
                        label: "Ticket",
                        value: ticketRef
                    )
                }

                // Story points
                if let points = editedCard.estimatedPoints {
                    MetadataRow(
                        icon: "number.circle",
                        label: "Story Points",
                        value: "\(points)"
                    )
                }

                // Due date
                if let dueDate = editedCard.dueDate {
                    MetadataRow(
                        icon: editedCard.isOverdue ? "exclamationmark.triangle.fill" : "calendar",
                        label: "Due Date",
                        value: formatFullDate(dueDate),
                        valueColor: editedCard.isOverdue ? .red : .rtTextPrimary
                    )
                }
            }
        }
    }

    // MARK: - Info Section

    private var infoSection: some View {
        VStack(alignment: .leading, spacing: 8) {
            Text("History")
                .font(.system(size: 10, weight: .semibold, design: .monospaced))
                .foregroundColor(.rtTextSecondary)
                .textCase(.uppercase)

            VStack(alignment: .leading, spacing: 6) {
                HStack {
                    Image(systemName: "clock")
                        .font(.system(size: 10))
                        .foregroundColor(.rtMuted)
                    Text("Created \(formatRelativeTime(editedCard.createdAt))")
                        .font(.system(size: 10, design: .monospaced))
                        .foregroundColor(.rtTextSecondary)
                }

                HStack {
                    Image(systemName: "clock.arrow.circlepath")
                        .font(.system(size: 10))
                        .foregroundColor(.rtMuted)
                    Text("Updated \(formatRelativeTime(editedCard.updatedAt))")
                        .font(.system(size: 10, design: .monospaced))
                        .foregroundColor(.rtTextSecondary)
                }

                if let completedAt = editedCard.completedAt {
                    HStack {
                        Image(systemName: "checkmark.circle")
                            .font(.system(size: 10))
                            .foregroundColor(.rtAccentGreen)
                        Text("Completed \(formatRelativeTime(completedAt))")
                            .font(.system(size: 10, design: .monospaced))
                            .foregroundColor(.rtTextSecondary)
                    }
                }

                HStack {
                    Image(systemName: "hourglass")
                        .font(.system(size: 10))
                        .foregroundColor(.rtMuted)
                    Text("Age: \(editedCard.ageInDays) days")
                        .font(.system(size: 10, design: .monospaced))
                        .foregroundColor(.rtTextSecondary)
                }
            }
            .padding(10)
            .frame(maxWidth: .infinity, alignment: .leading)
            .background(Color.rtBackgroundDark.opacity(0.3))
            .cornerRadius(6)
        }
    }

    // MARK: - Footer View

    private var footerView: some View {
        HStack {
            // Save button (only show if there are unsaved changes)
            if hasUnsavedChanges {
                Button(action: {
                    saveChanges()
                }) {
                    HStack(spacing: 6) {
                        Image(systemName: "square.and.arrow.down")
                            .font(.system(size: 12))
                        Text("Save Changes")
                            .font(.system(size: 11, weight: .medium, design: .monospaced))
                    }
                    .foregroundColor(.rtAccentGreen)
                    .padding(.horizontal, 12)
                    .padding(.vertical, 6)
                    .background(Color.rtAccentGreen.opacity(0.15))
                    .cornerRadius(6)
                }
                .buttonStyle(.plain)
            } else if editedCard != card {
                HStack(spacing: 6) {
                    Image(systemName: "checkmark.circle.fill")
                        .font(.system(size: 12))
                        .foregroundColor(.rtAccentGreen)
                    Text("Saved")
                        .font(.system(size: 10, design: .monospaced))
                        .foregroundColor(.rtTextSecondary)
                }
            }

            Spacer()

            // Delete button
            Button(action: {
                showingDeleteConfirmation = true
            }) {
                HStack(spacing: 6) {
                    Image(systemName: "trash")
                        .font(.system(size: 12))
                    Text("Delete Card")
                        .font(.system(size: 11, weight: .medium, design: .monospaced))
                }
                .foregroundColor(.red)
                .padding(.horizontal, 12)
                .padding(.vertical, 6)
                .background(Color.red.opacity(0.1))
                .cornerRadius(6)
                .overlay(
                    RoundedRectangle(cornerRadius: 6)
                        .stroke(Color.red.opacity(0.3), lineWidth: 1)
                )
            }
            .buttonStyle(.plain)
        }
    }

    // MARK: - Actions

    private func removeLabel(_ label: CardLabel) {
        editedCard.labels.removeAll { $0.id == label.id }
        saveChanges()
    }

    private func scheduleAutoSave() {
        hasUnsavedChanges = true

        // Cancel existing auto-save task
        autoSaveTask?.cancel()

        // Schedule new auto-save after 1 second of inactivity
        autoSaveTask = Task {
            try? await Task.sleep(nanoseconds: 1_000_000_000)

            if !Task.isCancelled {
                await MainActor.run {
                    saveChanges()
                }
            }
        }
    }

    private func saveChanges() {
        guard editedCard != card else {
            hasUnsavedChanges = false
            return
        }

        var updatedCard = editedCard
        updatedCard.updatedAt = Date()

        onUpdate(updatedCard)
        hasUnsavedChanges = false
    }

    // MARK: - Helpers

    private var priorityColor: Color {
        switch editedCard.priority {
        case .low:
            return .rtTextSecondary
        case .medium:
            return Color(hex: "2196F3")
        case .high:
            return Color(hex: "7B78AA")
        case .critical:
            return .red
        }
    }

    private func formatAssignee(_ assignee: String) -> String {
        if UUID(uuidString: assignee) != nil {
            return String(assignee.prefix(8))
        }
        return assignee
    }

    private func formatFullDate(_ date: Date) -> String {
        let formatter = DateFormatter()
        formatter.dateStyle = .medium
        formatter.timeStyle = .short
        return formatter.string(from: date)
    }

    private func formatRelativeTime(_ date: Date) -> String {
        let formatter = RelativeDateTimeFormatter()
        formatter.unitsStyle = .abbreviated
        return formatter.localizedString(for: date, relativeTo: Date())
    }
}

// MARK: - Label Chip

private struct LabelChip: View {
    let label: CardLabel
    let onRemove: () -> Void

    @State private var isHovering = false

    var body: some View {
        HStack(spacing: 4) {
            Text(label.name)
                .font(.system(size: 11, weight: .medium, design: .monospaced))
                .foregroundColor(Color(hex: label.color))

            if isHovering {
                Button(action: onRemove) {
                    Image(systemName: "xmark")
                        .font(.system(size: 8, weight: .bold))
                        .foregroundColor(Color(hex: label.color))
                }
                .buttonStyle(.plain)
            }
        }
        .padding(.horizontal, 8)
        .padding(.vertical, 4)
        .background(Color(hex: label.color).opacity(0.15))
        .cornerRadius(4)
        .overlay(
            RoundedRectangle(cornerRadius: 4)
                .stroke(Color(hex: label.color).opacity(0.3), lineWidth: 1)
        )
        .onHover { hovering in
            withAnimation(.easeInOut(duration: 0.15)) {
                isHovering = hovering
            }
        }
    }
}

// MARK: - Metadata Row

private struct MetadataRow: View {
    let icon: String
    let label: String
    let value: String
    var valueColor: Color = .rtTextPrimary

    var body: some View {
        HStack {
            HStack(spacing: 6) {
                Image(systemName: icon)
                    .font(.system(size: 11))
                    .foregroundColor(.rtMuted)
                    .frame(width: 16)

                Text(label)
                    .font(.system(size: 11, design: .monospaced))
                    .foregroundColor(.rtTextSecondary)
            }
            .frame(width: 120, alignment: .leading)

            Text(value)
                .font(.system(size: 11, weight: .medium, design: .monospaced))
                .foregroundColor(valueColor)

            Spacer()
        }
    }
}

// MARK: - Label Picker View

private struct LabelPickerView: View {
    @Binding var selectedLabels: [CardLabel]
    let onDismiss: () -> Void

    @State private var searchText = ""
    @State private var customLabelName = ""
    @State private var customLabelColor = "#9E9E9E"

    private var availableLabels: [CardLabel] {
        CardLabel.presets.filter { preset in
            !selectedLabels.contains(where: { $0.id == preset.id })
        }
    }

    private var filteredLabels: [CardLabel] {
        if searchText.isEmpty {
            return availableLabels
        } else {
            return availableLabels.filter { $0.name.localizedCaseInsensitiveContains(searchText) }
        }
    }

    var body: some View {
        VStack(spacing: 0) {
            // Header
            HStack {
                Text("Add Labels")
                    .font(.system(size: 14, weight: .semibold, design: .monospaced))
                    .foregroundColor(.rtTextPrimary)

                Spacer()

                Button(action: onDismiss) {
                    Image(systemName: "xmark.circle.fill")
                        .font(.system(size: 18))
                        .foregroundColor(.rtMuted)
                }
                .buttonStyle(.plain)
            }
            .padding()
            .background(Color.rtBackgroundDark)
            .overlay(
                Rectangle()
                    .frame(height: 1)
                    .foregroundColor(.rtBorderSubtle),
                alignment: .bottom
            )

            // Search
            HStack {
                Image(systemName: "magnifyingglass")
                    .font(.system(size: 12))
                    .foregroundColor(.rtMuted)

                TextField("Search labels...", text: $searchText)
                    .textFieldStyle(.plain)
                    .font(.system(size: 12, design: .monospaced))
            }
            .padding(10)
            .background(Color.rtBackgroundDark.opacity(0.5))
            .cornerRadius(6)
            .padding()

            // Available labels
            ScrollView {
                VStack(alignment: .leading, spacing: 12) {
                    if !filteredLabels.isEmpty {
                        Text("Available Labels")
                            .font(.system(size: 10, weight: .semibold, design: .monospaced))
                            .foregroundColor(.rtTextSecondary)
                            .textCase(.uppercase)

                        FlowLayout(spacing: 8) {
                            ForEach(filteredLabels) { label in
                                Button(action: {
                                    selectedLabels.append(label)
                                }) {
                                    Text(label.name)
                                        .font(.system(size: 11, weight: .medium, design: .monospaced))
                                        .foregroundColor(Color(hex: label.color))
                                        .padding(.horizontal, 8)
                                        .padding(.vertical, 4)
                                        .background(Color(hex: label.color).opacity(0.15))
                                        .cornerRadius(4)
                                }
                                .buttonStyle(.plain)
                            }
                        }
                    } else {
                        Text("No labels found")
                            .font(.system(size: 11, design: .monospaced))
                            .foregroundColor(.rtMuted)
                    }
                }
                .padding()
            }
        }
        .frame(width: 400, height: 500)
        .background(Color.rtBackgroundLight)
    }
}

// MARK: - Flow Layout

private struct FlowLayout: Layout {
    var spacing: CGFloat = 8

    func sizeThatFits(proposal: ProposedViewSize, subviews: Subviews, cache: inout ()) -> CGSize {
        let result = FlowResult(
            in: proposal.replacingUnspecifiedDimensions().width,
            subviews: subviews,
            spacing: spacing
        )
        return result.size
    }

    func placeSubviews(in bounds: CGRect, proposal: ProposedViewSize, subviews: Subviews, cache: inout ()) {
        let result = FlowResult(
            in: bounds.width,
            subviews: subviews,
            spacing: spacing
        )
        for (index, subview) in subviews.enumerated() {
            subview.place(at: result.positions[index], proposal: .unspecified)
        }
    }

    struct FlowResult {
        var size: CGSize = .zero
        var positions: [CGPoint] = []

        init(in maxWidth: CGFloat, subviews: Subviews, spacing: CGFloat) {
            var x: CGFloat = 0
            var y: CGFloat = 0
            var lineHeight: CGFloat = 0

            for subview in subviews {
                let size = subview.sizeThatFits(.unspecified)

                if x + size.width > maxWidth && x > 0 {
                    x = 0
                    y += lineHeight + spacing
                    lineHeight = 0
                }

                positions.append(CGPoint(x: x, y: y))
                x += size.width + spacing
                lineHeight = max(lineHeight, size.height)
            }

            self.size = CGSize(width: maxWidth, height: y + lineHeight)
        }
    }
}

// MARK: - View Extensions

extension View {
    func onKeyboardShortcut(_ key: KeyEquivalent, action: @escaping () -> Void) -> some View {
        self.background(
            Button("") {
                action()
            }
            .keyboardShortcut(key, modifiers: [])
            .hidden()
        )
    }

    func onFocus(_ action: @escaping (Bool) -> Void) -> some View {
        self.onAppear {
            // Track focus state
        }
    }
}

// MARK: - Preview

#if DEBUG
struct CardDetailView_Previews: PreviewProvider {
    static var previews: some View {
        CardDetailView(
            card: KanbanCard(
                title: "Implement user authentication",
                description: "Add JWT-based auth with refresh tokens and secure storage",
                status: .inProgress,
                labels: [.feature, .security],
                priority: .high,
                assignee: "frontend-morty",
                ticketRef: "RT-024",
                estimatedPoints: 8,
                source: .manual
            ),
            columnId: UUID(),
            onUpdate: { card in
                print("Updated card: \(card.title)")
            },
            onDelete: {
                print("Deleted card")
            }
        )
    }
}
#endif
