import SwiftUI
import UniformTypeIdentifiers

// MARK: - Kanban Card UTType

extension UTType {
    static let kanbanCard = UTType(exportedAs: "com.rick.terminal.kanban.card")
}

// MARK: - Kanban Card View

/// Visual representation of a single Kanban card
struct KanbanCardView: View {
    let card: KanbanCard
    var onClaim: (() -> Void)?
    var onTap: (() -> Void)?
    /// Called when the user starts dragging this card (passes card to parent for source-column tracking)
    var onDragStarted: ((KanbanCard) -> Void)?

    @State private var isHovering = false
    @State private var isDragging = false

    var body: some View {
        VStack(alignment: .leading, spacing: 6) {
            // Header with title and source badge
            HStack(alignment: .top, spacing: 6) {
                VStack(alignment: .leading, spacing: 4) {
                    Text(card.title)
                        .font(.system(size: 11, weight: .medium, design: .monospaced))
                        .foregroundColor(.rtTextPrimary)
                        .lineLimit(2)
                        .fixedSize(horizontal: false, vertical: true)

                    if !card.description.isEmpty {
                        Text(card.description)
                            .font(.system(size: 9, design: .monospaced))
                            .foregroundColor(.rtTextSecondary)
                            .lineLimit(2)
                    }
                }

                Spacer(minLength: 4)

                // Source badge
                sourceBadge
            }

            // Labels
            if !card.labels.isEmpty {
                labelsView
            }

            // Footer with metadata
            footerView
        }
        .padding(8)
        .frame(maxWidth: .infinity, alignment: .leading)
        .background(cardBackground)
        .cornerRadius(6)
        .overlay(
            RoundedRectangle(cornerRadius: 6)
                .stroke(borderColor, lineWidth: (isHovering || isDragging) ? 1.5 : 1)
        )
        .opacity(isDragging ? 0.5 : 1.0)
        .scaleEffect(isDragging ? 0.97 : 1.0)
        .animation(.easeInOut(duration: 0.15), value: isDragging)
        .contentShape(Rectangle())
        .onHover { hovering in
            withAnimation(.easeInOut(duration: 0.15)) {
                isHovering = hovering
            }
        }
        .onTapGesture {
            onTap?()
        }
        .onDrag {
            isDragging = true
            onDragStarted?(card)
            // Encode card ID as NSString for drag provider
            let provider = NSItemProvider(object: card.id.uuidString as NSString)
            provider.suggestedName = card.title
            return provider
        }
    }

    // MARK: - Source Badge

    private var sourceBadge: some View {
        HStack(spacing: 3) {
            Image(systemName: card.source.iconName)
                .font(.system(size: 8))
                .foregroundColor(sourceBadgeColor)

            if card.isAutoGenerated && isHovering {
                Button(action: {
                    onClaim?()
                }) {
                    Text("Claim")
                        .font(.system(size: 8, weight: .medium, design: .monospaced))
                        .foregroundColor(.rtAccentGreen)
                        .padding(.horizontal, 4)
                        .padding(.vertical, 2)
                        .background(Color.rtAccentGreen.opacity(0.15))
                        .cornerRadius(3)
                }
                .buttonStyle(.plain)
                .help("Claim this card to prevent auto-updates")
            }
        }
        .padding(.horizontal, 5)
        .padding(.vertical, 3)
        .background(sourceBadgeBackground)
        .cornerRadius(4)
    }

    private var sourceBadgeColor: Color {
        switch card.source {
        case .manual:
            return .rtAccentGreen
        case .claude:
            return .rtAccentPurple
        case .ticket:
            return Color(hex: "1E88E5")
        case .subAgent:
            return Color(hex: "FB8C00")
        }
    }

    private var sourceBadgeBackground: Color {
        sourceBadgeColor.opacity(0.15)
    }

    // MARK: - Labels View

    private var labelsView: some View {
        HStack(spacing: 4) {
            ForEach(card.labels.prefix(3)) { label in
                Text(label.name)
                    .font(.system(size: 8, weight: .medium, design: .monospaced))
                    .foregroundColor(Color(hex: label.color))
                    .padding(.horizontal, 4)
                    .padding(.vertical, 2)
                    .background(Color(hex: label.color).opacity(0.15))
                    .cornerRadius(3)
            }

            if card.labels.count > 3 {
                Text("+\(card.labels.count - 3)")
                    .font(.system(size: 8, design: .monospaced))
                    .foregroundColor(.rtMuted)
            }
        }
    }

    // MARK: - Footer View

    private var footerView: some View {
        HStack(spacing: 8) {
            // Priority indicator
            priorityView

            Spacer()

            // Assignee
            if let assignee = card.assignee, !assignee.isEmpty {
                HStack(spacing: 3) {
                    Image(systemName: "person.circle.fill")
                        .font(.system(size: 8))
                    Text(formatAssignee(assignee))
                        .font(.system(size: 8, design: .monospaced))
                }
                .foregroundColor(.rtTextSecondary)
            }

            // Due date / Overdue indicator
            if let dueDate = card.dueDate {
                HStack(spacing: 3) {
                    Image(systemName: card.isOverdue ? "exclamationmark.triangle.fill" : "calendar")
                        .font(.system(size: 8))
                    Text(formatDate(dueDate))
                        .font(.system(size: 8, design: .monospaced))
                }
                .foregroundColor(card.isOverdue ? .red : .rtTextSecondary)
            }

            // Story points
            if let points = card.estimatedPoints {
                HStack(spacing: 3) {
                    Image(systemName: "number.circle")
                        .font(.system(size: 8))
                    Text("\(points)")
                        .font(.system(size: 8, design: .monospaced))
                }
                .foregroundColor(.rtTextSecondary)
            }
        }
    }

    private var priorityView: some View {
        HStack(spacing: 2) {
            Image(systemName: card.priority.iconName)
                .font(.system(size: 8))
            Text(card.priority.displayName)
                .font(.system(size: 8, design: .monospaced))
        }
        .foregroundColor(priorityColor)
    }

    private var priorityColor: Color {
        switch card.priority {
        case .low:
            return .rtTextSecondary
        case .medium:
            return Color(hex: "2196F3")
        case .high:
            return Color(hex: "7B78AA")
        case .critical:
            return .red
        }
    }

    // MARK: - Computed Colors

    private var cardBackground: Color {
        if isHovering {
            return Color.rtBackgroundLight.opacity(0.8)
        } else {
            return Color.rtBackgroundDark.opacity(0.6)
        }
    }

    private var borderColor: Color {
        if card.isOverdue {
            return .red.opacity(0.5)
        } else if isDragging {
            return .rtAccentPurple.opacity(0.7)
        } else if isHovering {
            return .rtAccentGreen.opacity(0.5)
        } else {
            return .rtBorderSubtle
        }
    }

    // MARK: - Helpers

    private func formatAssignee(_ assignee: String) -> String {
        // If it is a UUID, show shortened version
        if UUID(uuidString: assignee) != nil {
            return String(assignee.prefix(8))
        }
        return assignee
    }

    private func formatDate(_ date: Date) -> String {
        let formatter = DateFormatter()
        let calendar = Calendar.current

        if calendar.isDateInToday(date) {
            formatter.dateFormat = "HH:mm"
            return "Today \(formatter.string(from: date))"
        } else if calendar.isDateInTomorrow(date) {
            return "Tomorrow"
        } else {
            formatter.dateFormat = "MMM d"
            return formatter.string(from: date)
        }
    }
}

// MARK: - Preview

#if DEBUG
struct KanbanCardView_Previews: PreviewProvider {
    static var previews: some View {
        VStack(spacing: 12) {
            KanbanCardView(
                card: KanbanCard(
                    title: "Implement user authentication",
                    description: "Add JWT-based auth with refresh tokens",
                    status: .inProgress,
                    labels: [.feature, .security],
                    priority: .high,
                    assignee: "frontend-morty",
                    estimatedPoints: 8
                )
            )
            KanbanCardView(
                card: KanbanCard(
                    title: "Fix TypeScript compilation errors",
                    description: "",
                    status: .inProgress,
                    labels: [.bug],
                    priority: .medium,
                    source: .claude(sourceHash: "abc123def456")
                ),
                onClaim: { print("Card claimed!") }
            )
        }
        .padding()
        .background(Color.rtBackgroundDark)
        .previewLayout(.sizeThatFits)
    }
}
#endif
